version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=mydb
    networks:
      - app-network

  database:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=example
      - POSTGRESQL_DATABASE=mydb
    volumes:
      - db-data:/bitnami/postgresql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql  # 新增初始化脚本挂载
    networks:
      - app-network
volumes:
  db-data:

networks:
  app-network:
    driver: bridge